server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vote?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  elasticsearch:
    rest:
      uris: 192.168.127.129:9200
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 2000
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 30
        min-idle: 0
  rabbitmq:
    host: 175.178.255.153
    port: 5672
    username: wet
    password: wet2022
    virtual-host: dev
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
