spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 1200
      keep-alive: true
      remove-abandoned: true
      remove-abandoned-timeout: 180
      filters: stat
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid



server:
  servlet:
    context-path: /v1


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/**/**.xml

qywx:
  corpId: wxcc62e7701c249c74
  secret: 2LWfP-Diy4Rf2A5ReRaIJ88P-oRVrSs4aVHHj5RmKmo
  agentId: 1000001
  token: 111
  aesKey: 111

service:
  domain: http://gktdby.natappfree.cc